"""initial_tables

Revision ID: 597219a556ce
Revises: 
Create Date: 2025-11-13 11:14:38.092168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '597219a556ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discipline_zone_sequences_discipline'), table_name='discipline_zone_sequences')
    op.drop_index(op.f('ix_discipline_zone_sequences_project_id'), table_name='discipline_zone_sequences')
    op.drop_table('discipline_zone_sequences')
    op.add_column('projects', sa.Column('owner', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('zone_sequences', sa.JSON(), nullable=False, server_default='{}'))
    op.drop_column('projects', 'client_name')
    op.add_column('user_task_templates', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('user_task_templates', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('user_task_templates', sa.Column('max_equipm_allowed', sa.Integer(), nullable=True))
    op.drop_column('user_task_templates', 'resource_priority')
    op.drop_column('user_task_templates', 'preferred_equipment')
    op.add_column('users', sa.Column('superviser', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'superviser')
    op.add_column('user_task_templates', sa.Column('preferred_equipment', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_task_templates', sa.Column('resource_priority', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_task_templates', 'max_equipm_allowed')
    op.drop_column('user_task_templates', 'unit')
    op.drop_column('user_task_templates', 'quantity')
    op.add_column('projects', sa.Column('client_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('projects', 'zone_sequences')
    op.drop_column('projects', 'owner')
    op.create_table('discipline_zone_sequences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('discipline', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('discipline_zone_sequences_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('discipline_zone_sequences_pkey'))
    )
    op.create_index(op.f('ix_discipline_zone_sequences_project_id'), 'discipline_zone_sequences', ['project_id'], unique=False)
    op.create_index(op.f('ix_discipline_zone_sequences_discipline'), 'discipline_zone_sequences', ['discipline'], unique=False)
    # ### end Alembic commands ###
