"""Add new tables

Revision ID: 9a6bcb129976
Revises: a4628df1e535
Create Date: 2025-11-17 16:43:11.254262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a6bcb129976'
down_revision: Union[str, Sequence[str], None] = 'a4628df1e535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_templates_is_active'), 'resource_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_resource_templates_user_id'), 'resource_templates', ['user_id'], unique=False)
    op.create_table('equipment_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('base_count', sa.Integer(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=True),
    sa.Column('capacity', sa.String(length=100), nullable=True),
    sa.Column('max_units_per_task', sa.Integer(), nullable=True),
    sa.Column('base_productivity_rate', sa.Float(), nullable=True),
    sa.Column('productivity_unit', sa.String(length=50), nullable=True),
    sa.Column('requires_operator', sa.Boolean(), nullable=True),
    sa.Column('operator_type', sa.String(length=100), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['resource_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_resources_code'), 'equipment_resources', ['code'], unique=True)
    op.create_index(op.f('ix_equipment_resources_is_active'), 'equipment_resources', ['is_active'], unique=False)
    op.create_index(op.f('ix_equipment_resources_template_id'), 'equipment_resources', ['template_id'], unique=False)
    op.create_index(op.f('ix_equipment_resources_user_id'), 'equipment_resources', ['user_id'], unique=False)
    op.create_table('worker_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('base_count', sa.Integer(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=True),
    sa.Column('max_workers_per_crew', sa.Integer(), nullable=True),
    sa.Column('base_productivity_rate', sa.Float(), nullable=True),
    sa.Column('productivity_unit', sa.String(length=50), nullable=True),
    sa.Column('qualification_level', sa.String(length=50), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['resource_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_resources_code'), 'worker_resources', ['code'], unique=True)
    op.create_index(op.f('ix_worker_resources_is_active'), 'worker_resources', ['is_active'], unique=False)
    op.create_index(op.f('ix_worker_resources_template_id'), 'worker_resources', ['template_id'], unique=False)
    op.create_index(op.f('ix_worker_resources_user_id'), 'worker_resources', ['user_id'], unique=False)
    op.drop_index(op.f('ix_resources_is_active'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_user_id'), table_name='resources')
    op.drop_table('resources')
    op.add_column('schedule_tasks', sa.Column('allocated_equipments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('schedule_tasks', 'actual_end_date')
    op.drop_column('schedule_tasks', 'allocated_equipment')
    op.drop_column('schedule_tasks', 'completion_percentage')
    op.drop_column('schedule_tasks', 'actual_start_date')
    op.add_column('user_task_templates', sa.Column('max_equipment_allowed', sa.Integer(), nullable=True))
    op.add_column('user_task_templates', sa.Column('template_name', sa.String(length=20), nullable=True))
    op.drop_column('user_task_templates', 'max_equipm_allowed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_task_templates', sa.Column('max_equipm_allowed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_task_templates', 'template_name')
    op.drop_column('user_task_templates', 'max_equipment_allowed')
    op.add_column('schedule_tasks', sa.Column('actual_start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('schedule_tasks', sa.Column('completion_percentage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schedule_tasks', sa.Column('allocated_equipment', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('schedule_tasks', sa.Column('actual_end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('schedule_tasks', 'allocated_equipments')
    op.create_table('resources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hourly_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('productivity_rates', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('equipment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('max_crews', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('max_equipment', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('efficiency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('availability_schedule', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('maintenance_schedule', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('resources_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('resources_pkey'))
    )
    op.create_index(op.f('ix_resources_user_id'), 'resources', ['user_id'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_is_active'), 'resources', ['is_active'], unique=False)
    op.drop_index(op.f('ix_worker_resources_user_id'), table_name='worker_resources')
    op.drop_index(op.f('ix_worker_resources_template_id'), table_name='worker_resources')
    op.drop_index(op.f('ix_worker_resources_is_active'), table_name='worker_resources')
    op.drop_index(op.f('ix_worker_resources_code'), table_name='worker_resources')
    op.drop_table('worker_resources')
    op.drop_index(op.f('ix_equipment_resources_user_id'), table_name='equipment_resources')
    op.drop_index(op.f('ix_equipment_resources_template_id'), table_name='equipment_resources')
    op.drop_index(op.f('ix_equipment_resources_is_active'), table_name='equipment_resources')
    op.drop_index(op.f('ix_equipment_resources_code'), table_name='equipment_resources')
    op.drop_table('equipment_resources')
    op.drop_index(op.f('ix_resource_templates_user_id'), table_name='resource_templates')
    op.drop_index(op.f('ix_resource_templates_is_active'), table_name='resource_templates')
    op.drop_table('resource_templates')
    # ### end Alembic commands ###
