"""add duration fields to user task templates

Revision ID: a4628df1e535
Revises: 597219a556ce
Create Date: 2025-11-13 16:42:35.018949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4628df1e535'
down_revision: Union[str, Sequence[str], None] = '597219a556ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_task_templates', sa.Column('unit_duration', sa.Integer(), nullable=True))
    op.add_column('user_task_templates', sa.Column('duration_calculation_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_task_templates', 'duration_calculation_method')
    op.drop_column('user_task_templates', 'unit_duration')
    # ### end Alembic commands ###
